#!/usr/bin/env bash

set -euo pipefail

actions() {
  echo "$(cd "$(dirname "${0}")/../../" && pwd)"
}

is-protected() {
  local name=$(git rev-parse --abbrev-ref HEAD)

  case "${name}" in
    devel | main | master )
      echo 1 ;;
    *)
      echo 0 ;;
  esac
}

protected-branch() {
  local branch=$(git rev-parse --abbrev-ref HEAD)

  case "$1" in
    /etc/nixos | $HOME/local/dot* ) exit 0 ;;
    $HOME/local/githooks | $HOME/local/textlintrc ) exit 0 ;;
  esac

  if test $(is-protected "${branch}") -eq 1 ; then
    echo this branch is protected
    exit 1
  fi
}

protected-branch "${1}" "${2}"
