#!/usr/bin/env bash

set -euo pipefail

lint-secret() {
  export NODE_PATH="${2}/node_modules"

  if test -e "${1}/.secretlintrc.json" ; then
    $NODE_PATH/.bin/secretlint --secretlintrc="${1}/.secretlintrc.json" '**/*'
  fi
    
  $NODE_PATH/.bin/secretlint --secretlintrc="${2}/.secretlintrc.json" '**/*'

  exit 0
}

lint-secret "$1" "$2"
