#!/usr/bin/env bash

set -euo pipefail

lint-secret() {
  export NODE_PATH="${2}/node_modules"

  local cmdline="${NODE_PATH}/.bin/secretlint"
  if test -e "${1}/.gitignore"; then
    export cmdline="${cmdline} --secretlintignore ${1}/.gitignore";
  fi

  if test -e "${1}/.secretlintrc.json"; then
    $cmdline --secretlintrc "${1}/.secretlintrc.json" "**/*"
  fi

  exit 0
}

lint-secret "$1" "$2"
