rules:
  rousseau:
    ignoreTypes:
      - sentence:uppercase
    showLevels:
      - suggestion
      - warning
      - error
  alex:
    allow: []
  common-misspellings:
    ignore: []
  stop-words:
    defaultWords: true
    skip:
      - Blockquote
  en-capitalization: true,
  en-spell: true,
  unexpanded-acronym:
    - min_acronym_len: 3
  write-good:
    passive: true
    illusion: true
    so: true
    thereIs: true
    weasel: true
    tooWordy: true
    cliches: true
