#!/usr/bin/env bash

set -euo pipefail

textlintrc() {
  for file in .textlintrc .textlintrc.yaml .textlintrc.yml .textlintrc.json ; do
    local fp=$HOME/local/githooks/$file
    if test -e .git/locale && test -e "$fp.$(cat .git/locale)"; then
      echo "$fp.$(cat .git/locale)"
      return 0
    elif test -e $fp ; then
      echo $fp
      return 0
    fi
  done

  echo .textlintrc
  return 0
}

githooks() {
  echo $HOME/local/githooks
  return 0
}

main() {
  local MSG=$1
  local textlintrc="$(textlintrc)"

  export NODE_PATH="$(githooks)/node_modules"
  $NODE_PATH/.bin/commitlint --config "$(githooks)/.commitlintrc.json" --edit "$1" || exit 1
  cat "$1" | $NODE_PATH/.bin/textlint --config $textlintrc --stdin || exit 1

  return 0
}

main "$1"
