#!/usr/bin/env bash

set -euo pipefail

textlintrc() {

  for file in .textlintrc .textlintrc.yaml .textlintrc.yml .textlintrc.json ; do
    if test -e .git/locale && test -e "$file.$(cat .git/locale)"; then
      echo "$file.$(cat .git/locale)"
      return 0
    elif test -e $file ; then
      echo $file
      return 0
    fi
  done

  echo .textlintrc
  return 0
}

githooks() {
  echo "$(cd "$(dirname "${0}")/../../" && pwd)"
  return 0
}

main() {
  local MSG=$1
  local textlintrc="$(textlintrc)"

  export NODE_PATH="$(githooks)/node_modules"
  $NODE_PATH/.bin/commitlint --config "$(githooks)/.commitlintrc.json" --edit "$1" || exit 1
  cat "$1" | $NODE_PATH/.bin/textlint --config $textlintrc --stdin || exit 1

  return 0
}

main "$1"
