#!/usr/bin/env bash

set -euo pipefail

hooks() {
  echo "$(cd "$(dirname "${0}")/../" && pwd)"
}

actions() {
  echo "$(hooks)/actions"
}

repository() {
  git rev-parse --show-superproject-working-tree --show-toplevel | head -1
}

commit-msg() {
  local actions="$(actions)"
  local repo="$(repository)"

  for action in $(ls "${actions}/commit-msg"); do
    bash "${actions}/commit-msg/${action}" "${1}" || exit 1
  done

  if test "${repo}/.git" != "${repo}/.git" ; then
    local hook="${repo}/hooks/$(basename "${0}")"
    if test -x "${hook}" ; then
      exec $hook
    fi
  fi

  exit 0
}

commit-msg "$1"
