#!/usr/bin/env bash

set -euo pipefail

dest-dir() {
  git rev-parse --show-superproject-working-tree --show-toplevel | head -1
}

src-dir() {
  echo "$(cd "$(dirname "${0}")/../" && pwd)"
}

lint-secret() {
  export NODE_PATH="$(src-dir)/node_modules"
  
  if test -e "$(dest-dir)/.secretlintrc.json" ; then
    $NODE_PATH/.bin/secretlint --secretlintrc=$(src-dir)/.secretlintrc.json '**/*'
    $NODE_PATH/.bin/secretlint --secretlintrc=$(dest-dir)/.secretlintrc.json '**/*'
  fi
}

lint() {
  if ! lint-secret ; then
    return 1
  fi

  local repo=$(dest-dir)/.git
  local hooks=$(src-dir)/.git

  if test "${repo}" != "${hooks}" ; then
    local hook="${repo}/hooks/$(basename "${0}")"

    if test -x "${hook}"; then
      exec $hook
    fi
  fi

  return 0
}

lint
