#!/usr/bin/env bash

git-dir() {
  git rev-parse --show-superproject-working-tree --show-toplevel | head -1
}

hooks-dir() {
  echo "$(cd "$(dirname "${0}")/../" && pwd)"
}

lint-secret() {
  local NODE_PATH=$(cd "$(dirname "${0}")/../node_modules")
  local cwd="$(pwd)"

  cd "$(git-dir)"
  npx --no-install -- secretlint '**/*'
  cd $cwd
}

lint() {
  if ! lint-secret ; then
    return 1
  fi

  local repo=$(git-dir)/.git
  local hooks=$(hooks-dir)/.git

  if test "${repo}" != "${hooks}" ; then
    local hook="${repo}/hooks/$(basename "${0}")"
    exec $hook
  fi

  return 0
}

lint "$1"
