#!/usr/bin/env bash

set -euo pipefail

hooks() {
  echo "$(cd "$(dirname "${0}")/../" && pwd)"
}

actions() {
  echo "$(hooks)/actions"
}

repository() {
  git rev-parse --show-superproject-working-tree --show-toplevel | head -1
}

pre-commit() {
  local actions="$(actions)"
  local repo="$(repository)"

  for action in $(ls "${actions}/pre-commit"); do
    bash "${actions}/pre-commit/${action}" "${repo}" "${actions%*/*}" || exit 1
  done

  if test "$(repository)/.git" != "$(repository)/.git" ; then
    local hook="$(repository)/hooks/$(basename "${0}")"
    if test -x "${hook}" ; then
      exec $hook
    fi
  fi

  exit 0
}

pre-commit
