#!/usr/bin/env bash

set -euo pipefail

actions() {
  echo "$(cd "$(dirname "${0}")/../../" && pwd)"
}

textlintrc() {
  local dotgit="$(dirname "$1")";

  if test -e "${dotgit}/.locale"; then
    echo .textlintrc.yaml."$(cat "${dotgit}/.locale")";
  else
    echo .textlintrc.yaml.en
  fi
}

lint-commit-message() {
  local actions="$(actions)"
  local textlintrc="$(textlintrc "$1")"

  export NODE_PATH="${actions}/node_modules"
  $NODE_PATH/.bin/commitlint --config "${actions}/.commitlintrc.json" --edit "$1" || exit 1
  cat "$1" | $NODE_PATH/.bin/textlint --config "${actions}/${textlintrc}" --stdin || exit 1
}

lint-commit-message "$1" && exit 0
